services:
  bun_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clinica_bun_app
    environment:
      DB_HOST: "clinica.cq3gc4ceq61b.us-east-1.rds.amazonaws.com"
      DB_USER: "admin"
      DB_PASSWORD: "SQL.awsKamKon1"
      DB_NAME: "ClinicaF"
      DB_PORT: "1433"
      APP_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped