events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index FamKon_Clinic.html index.html;
        
        location / {
            try_files $uri $uri/ /FamKon_Clinic.html;
        }
    }
}